POST http://localhost:3000/api/neighborhoods
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYjEyMzQiLCJpZCI6MSwiaWF0IjoxNjgzNDY4NTc5LCJleHAiOjE2ODM0NzIxNzl9.25r7LVZXP4yij2BhgJO9_ezBfj6eKZUir6ThZ5mqqXQ

{
  "name": "bobs-neighborhood-3"
}

###
POST http://localhost:3000/api/neighborhoods
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5zbWl0aCIsImlkIjoxLCJpYXQiOjE2ODMzMjg3OTMsImV4cCI6MTY4MzMzMjM5M30.iQYoXbI3U7Ezb02xxqB6Q9Evdz-T5VB1_xiqBeFeFFY

{
  "name": "foo"
}

###
POST http://localhost:3000/api/neighborhoods
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5zbWl0aCIsImlkIjoxLCJpYXQiOjE2ODMzMjg3OTMsImV4cCI6MTY4MzMzMjM5M30.iQYoXbI3U7Ezb02xxqB6Q9Evdz-T5VB1_xiqBeFeFFY

{
  "name": "foo"
}