
POST http://localhost:3001/api/responses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYjEyMzQiLCJpZCI6MSwiaWF0IjoxNjg5MjYwMDY1LCJleHAiOjE2OTI4NjAwNjV9.P55Oa3dLLVzKFkTkRcPr9CYp4JQms7D1pVPJa1WkWu4

{
  "content": "barbar",
  "request_id": 4
}