POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "bob1234",
  "password": "secret"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "johns",
  "password": "secret",
  "email": "john@example.com"
}