# Bob's Neighborhood Id is 1
POST http://localhost:3001/api/requests
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYjEyMzQiLCJpZCI6MSwiaWF0IjoxNjg4NjM2MzU5LCJleHAiOjE2OTIyMzYzNTl9.QoWeDWXXrm3KqbNO9JJ2bTZ_WqiSq4hULdlujq-hpvA

{
  "title": "foofoo",
  "content": "barbar",
  "neighborhoodId": 1
}