POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "johnsmith",
  "password": "secret"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "johnsmith",
  "password": "secret"
}