DELETE http://localhost:3001/api/responses/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFudG9uaW5hIiwiaWQiOjIsImlhdCI6MTY5NzA5NjU4MCwiZXhwIjoxNzAwNjk2NTgwfQ.GYtlSFw3sovkNlKx9I9uuP2rl3mbbaLZz8zz3mvd7K4