DELETE http://localhost:3001/api/neighborhoods/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYjEyMzQiLCJpZCI6MSwiaWF0IjoxNjg1MTk0NjU1LCJleHAiOjE2ODUxOTgyNTV9.b9v5InZEy047mXMKEtFmu0w7QrWZt5wh7LzWiAKSpPE

