# should work provided neighborhood with id 2 exists
PUT http://localhost:3001/api/neighborhoods/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYjEyMzQiLCJpZCI6MSwiaWF0IjoxNjg1NjE3MjU4LCJleHAiOjE2ODU2MjA4NTh9.BNbd4wnOPiOpqh9wCMU3BLeXs0cNnTZxlqpJMSc8tFY

{
  "name": "Test",
  "description": "Test",
  "location": "Athens"
}

# should fail with a 400
# PUT http://localhost:3000/api/neighborhoods/2
# Content-Type: application/json

# {
#   "name": "Test",
#   "description": "Test",
#   "location": "Athens",
#   "invalid": "Non-existent prop"
# }

# should fail with a 404 provided neighborhood with id 20939 doesn't exist
# PUT http://localhost:3000/api/neighborhoods/20939
# Content-Type: application/json

# {
#   "name": "Test",
#   "description": "Test",
#   "location": "Athens"
# }