POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "bob1234",
  "password": "secret"
}

### wrong username
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "bob12345",
  "password": "secret"
}

### wrong password
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "bob1234",
  "password": "secret1"
}
