name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    defaults:
      run:
        working-directory: ./backend
    runs-on: ubuntu-20.04
    name: Build pipeline
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
      - name: Check styles
        run: npm run lint
  test:
    defaults:
      run:
        working-directory: ./backend

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run tests
        uses: cloudposse/github-action-docker-compose-test-run@main
        with:
          registry: my-registry
          file: docker-compose.dev.yaml
          service: app
          command: npm test
